"""empty message

Revision ID: 14273d1f70d8
Revises: 690232dda677
Create Date: 2025-05-07 15:52:52.754470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14273d1f70d8'
down_revision = '690232dda677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('sobrenome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
