"""empty message

Revision ID: 529f7de41a41
Revises: e56937b3de9e
Create Date: 2025-05-16 10:06:10.798009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529f7de41a41'
down_revision = 'e56937b3de9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=False))
        batch_op.alter_column('sobrenome',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['sobrenome'])
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('senha')
        batch_op.drop_column('nome')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('senha', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('sobrenome',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('password_hash')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
