"""inclusao de campo respondido na tabela contato

Revision ID: 690232dda677
Revises: 3572e4873859
Create Date: 2025-04-24 19:32:32.363628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '690232dda677'
down_revision = '3572e4873859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respondido', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.drop_column('respondido')

    # ### end Alembic commands ###
