"""empty message

Revision ID: e56937b3de9e
Revises: adab62f244d1
Create Date: 2025-05-13 13:17:43.655822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e56937b3de9e'
down_revision = 'adab62f244d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contato')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contato',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data_envio', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('assunto', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mensagem', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('respondido', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='contato_pkey')
    )
    # ### end Alembic commands ###
